//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VandaEngine1.rc
//
#define IDOK2                           2
#define IDCLEAR                         2
#define IDCLEAN                         2
#define ID_BUTTON_WATER_DUDV            3
#define ID_BUTTON_AMBIENT_SOUND         3
#define ID_ACIVATE_AND_RENDER           3
#define IDCANCLE                        3
#define IDOK3                           3
#define ID_REMOVE_TEXT                  3
#define ID_BUTTON_WATER_NORMAL          4
#define IDATTACH                        5
#define IDDETACH                        6
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_VANDAENGINE_DIALOG          102
#define IDI_VANDAENGINE                 127
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDC_MOVE                        134
#define IDC_DEFAULT                     135
#define IDC_DEFAULT_ARROW               135
#define IDC_CURSOR1                     139
#define IDC_ZOOMIN                      139
#define IDD_DIALOG1                     141
#define IDD_DIALOG_ADD_LIGHT            141
#define IDD_DIALOG_ADD_WATER            143
#define IDD_DIALOG_ADD_AMBIENT_SOUND    144
#define IDB_BITMAP_SCENE_LIST           147
#define IDB_BITMAP_PHYSX_LOGO           152
#define IDB_BITMAP_OPENAL_LOGO          153
#define IDB_BITMAP1                     154
#define IDB_BITMAP_OPENGL3_LOGO         154
#define IDD_DIALOG_ADD_STATIC_SOUND     155
#define IDD_DIALOG_ADD_SKYDOM           156
#define IDD_DIALOG_WATER_ATTACHMENT     157
#define IDD_DIALOG_SELECT_CAMERA        158
#define IDI_ICON1                       165
#define IDB_BITMAP_NEW_UP               170
#define IDB_BITMAP_SAVE_UP              172
#define IDB_BITMAP_SAVE_DOWN            174
#define IDB_BITMAP_SAVE_FOCUS           176
#define IDB_BITMAP_NEW_DOWN             177
#define IDB_BITMAP_NEW_FOCUS            178
#define IDB_BITMAP_COLLADA_DOWN         179
#define IDB_BITMAP_COLLADA_FOCUS        180
#define IDB_BITMAP_COLLADA_UP           181
#define IDB_BITMAP_PHYSX_DOWN           182
#define IDB_BITMAP_PHYSX_FOCUS          183
#define IDB_BITMAP_PHYSX_UP             184
#define IDB_BITMAP_ANIM_PREV_DOWN       185
#define IDB_BITMAP_ANIM_PREV_FOCUS      186
#define IDB_BITMAP_ANIM_PREV_UP         187
#define IDB_BITMAP_OPEN_DOWN            188
#define IDB_BITMAP_OPEN_FOCUS           189
#define IDB_BITMAP_OPEN_UP              190
#define IDB_BITMAP_SAVEAS_UP            191
#define IDB_BITMAP_SAVEAS_DOWN          192
#define IDB_BITMAP_SAVEAS_FOCUS         193
#define IDB_BITMAP_ANIM_PREV_DISABLE    194
#define IDB_BITMAP_ANIM_PLAY_DISABLE    195
#define IDB_BITMAP_ANIM_PLAY_DOWN       196
#define IDB_BITMAP_ANIM_PLAY_FOCUS      197
#define IDB_BITMAP_ANIM_PLAY_UP         198
#define IDB_BITMAP_ANIM_NEXT_DISABLE    199
#define IDB_BITMAP_ANIM_NEXT_DOWN       200
#define IDB_BITMAP_ANIM_NEXT_FOCUS      201
#define IDB_BITMAP_ANIM_NEXT_UP         202
#define IDC_CUSTOM_HAND                 203
#define IDB_BITMAP_TIMER_DOWN           205
#define IDB_BITMAP_TIMER_FOCUS          206
#define IDB_BITMAP_TIMER_UP             207
#define IDB_BITMAP_ANIM_PAUSE_DISABLE   208
#define IDB_BITMAP_ANIM_PAUSE_DOWN      209
#define IDB_BITMAP_ANIM_PAUSE_FOCUS     210
#define IDB_BITMAP_ANIM_PAUSE_UP        211
#define IDB_BITMAP_WEB_DOWN             212
#define IDB_BITMAP_WEB_FOCUS            213
#define IDB_BITMAP_WEB_UP               214
#define IDB_BITMAP_FACEBOOK_DOWN        215
#define IDB_BITMAP_FACEBOOK_FOCUS       216
#define IDB_BITMAP_FACEBOOK_UP          217
#define IDB_BITMAP_DELETE_DOWN          220
#define IDB_BITMAP_DELETE_FOCUS         221
#define IDB_BITMAP_DELETE_UP            222
#define IDB_BITMAP_DELETE_DISABLE       223
#define IDB_BITMAP_EDIT_DISABLE         224
#define IDB_BITMAP_EDIT_DOWN            225
#define IDB_BITMAP_EDIT_FOCUS           226
#define IDB_BITMAP_EDIT_UP              227
#define IDB_BITMAP_MATERIAL_DISABLE     228
#define IDB_BITMAP_MATERIAL_DOWN        229
#define IDB_BITMAP_MATERIAL_UP          231
#define IDB_BITMAP_MATERIAL_FOCUS       232
#define IDD_DIALOG_EDIT_MATERIAL        233
#define IDB_BITMAP_SKY_DISABLE          234
#define IDB_BITMAP_SKY_DOWN             235
#define IDB_BITMAP_SKY_FOCUS            236
#define IDB_BITMAP_SKY_UP               237
#define IDB_BITMAP_STATICSOUND_DOWN     238
#define IDB_BITMAP_STATICSOUND_FOCUS    239
#define IDB_BITMAP_STATICSOUND_UP       240
#define IDB_BITMAP_AMBIENTSOUND_DISABLE 241
#define IDB_BITMAP_AMBIENTSOUND_DOWN    242
#define IDB_BITMAP_AMBIENTSOUND_FOCUS   243
#define IDB_BITMAP_AMBIENTSOUND_UP      244
#define IDB_BITMAP_LIGHT_DOWN           245
#define IDB_BITMAP_LIGHT_FOCUS          246
#define IDB_BITMAP_LIGHT_UP             247
#define IDB_BITMAP_WATER_DOWN           248
#define IDB_BITMAP_WATER_FOCUS          249
#define IDB_BITMAP_WATER_UP             250
#define IDB_BITMAP_PLAYER_DOWN          251
#define IDB_BITMAP_PLAYER_FOCUS         252
#define IDB_BITMAP_PLAYER_UP            253
#define IDB_BITMAP_CONSOLE_DOWN         254
#define IDB_BITMAP_CONSOLE_FOCUS        255
#define IDB_BITMAP_CONSOLE_UP           256
#define IDD_DIALOG_CONSOLE              257
#define IDB_BITMAP_SUMMARY_DOWN         258
#define IDB_BITMAP_SUMMARY_FOCUS        259
#define IDB_BITMAP_SUMMARY_UP           260
#define IDD_DIALOG_WARNINGS             261
#define IDD_DIALOG_SHADOW               262
#define IDD_DIALOG_DOF                  265
#define IDD_DIALOG_FOG                  266
#define IDD_DIALOG_BLOOM                267
#define IDC_POINTER                     268
#define IDR_RT_ANICURSOR                269
#define IDB_BITMAP_OBJECTLIST_CAMERA    270
#define IDB_BITMAP_OBJECTLIST_IMAGE     271
#define IDB_BITMAP_OBJECTLIST_MATERIAL  272
#define IDB_BITMAP_OBJECTLIST_MESH      273
#define IDB_BITMAP_OBJECTLIST_ANIMATION 274
#define IDB_BITMAP_OBJECTLIST_LIGHT     275
#define IDB_BITMAP_OBJECTLIST_EFFECT    276
#define IDB_BITMAP_OBJECTLIST_ANIMATIONCLIP 277
#define IDB_BITMAP_OBJECTLIST_SKINCONTROLLER 278
#define IDB_BITMAP_ENGINEOBJECTLIST_AMBIENTSOUND 279
#define IDB_BITMAP_ENGINEOBJECTLIST_LIGHT 280
#define IDB_BITMAP_ENGINEOBJECTLIST_SKY 281
#define IDB_BITMAP_ENGINEOBJECTLIST_STATICSOUND 282
#define IDB_BITMAP_ENGINEOBJECTLIST_WATER 283
#define IDC_UNAVAILABLE                 284
#define IDD_DIALOG_WELCOME              285
#define IDB_BITMAP_WELCOME_VISIT_HELP_DOWN 286
#define IDB_BITMAP_WELCOME_VISIT_HELP_FOCUS 287
#define IDB_BITMAP4                     288
#define IDB_BITMAP_WELCOME_VISIT_HELP_UP 288
#define IDB_BITMAP2                     289
#define IDB_BITMAP_WELCOME_UNCHECK      289
#define IDB_BITMAP_WELCOME_CHECK        290
#define IDB_BITMAP_WELCOME_VIDEO_DOWN   291
#define IDB_BITMAP_WELCOME_VIDEO_FOCUS  292
#define IDB_BITMAP_WELCOME_VIDEO_UP     293
#define IDD_DIALOG_OPTIONS              294
#define IDB_BITMAP_PHYSXELEMENTLIST_DYNAMICRIGIDBODY 295
#define IDD_DIALOG_EDIT_LIGHT           297
#define IDD_DIALOG_SCENE_OPTIONS        298
#define IDB_BITMAP_VANDA_LOGO           299
#define IDB_BITMAP_VANDA_TEXT           301
#define IDB_BITMAP_VANDA_LOGO2          302
#define IDB_BITMAP_VANDA_TEXT2          303
#define IDD_DIALOG_AMBIENT              304
#define IDB_BITMAP_WELCOME_GIFT_UP      305
#define IDB_BITMAP_WELCOME_GIFT_DOWN    306
#define IDB_BITMAP_WELCOME_GIFT_FOCUS   307
#define IDB_BITMAP_SEPARATOR            308
#define IDB_BITMAP_TWITTER_DOWN         309
#define IDB_BITMAP_TWITTER_FOCUS        310
#define IDB_BITMAP_TWITTER_UP           311
#define IDB_BITMAP_YOUTUBE_DOWN         312
#define IDB_BITMAP_YOUTUBE_FOCUS        313
#define IDB_BITMAP_YOUTUBE_UP           314
#define IDB_BITMAP_WELCOME_TUTORIAL_UP  315
#define IDB_BITMAP_WELCOME_TUTORIAL_DOWN 316
#define IDB_BITMAP_WELCOME_TUTORLA_FOCUS 317
#define IDB_BITMAP_WELCOME_TUTORIAL_FOCUS 317
#define IDB_BITMAP_SCRIPT_DOWN          318
#define IDB_BITMAP_SCRIPT_FOCUS         319
#define IDB_BITMAP_SCRIPT_UP            320
#define IDB_BITMAP_PUBLISH_DOWN         321
#define IDB_BITMAP_PUBLISH_FOCUS        322
#define IDB_BITMAP_PUBLISH_UP           323
#define IDB_BITMAP_CAMERA_DOWN          324
#define IDB_BITMAP_CAMERA_FOCUS         325
#define IDB_BITMAP_CAMERA_UP            326
#define IDB_BITMAP_VANDA_VERSION        327
#define IDD_DIALOG2                     328
#define IDD_DIALOG_EDIT_SCENEMANAGER    328
#define IDB_BITMAP3                     329
#define IDB_BITMAP_VANDA_RTI            329
#define IDB_BITMAP_OVERVIEW_UP          330
#define IDB_BITMAP_OVERVIEW_DOWN        331
#define IDB_BITMAP_OVERVIEW_FOCUS       332
#define IDB_BITMAP_PHYSXELEMENTLIST_TRIGGER 333
#define IDB_BITMAP5                     334
#define IDB_BITMAP_PHYSXELEMENTLIST_STATICRIGIDBODY 334
#define IDD_DIALOG_SAVE                 336
#define IDD_DIALOG_PUBLISH_PROJECT      337
#define IDB_BITMAP_LOGO_PUBLISH         338
#define IDD_DIALOG_SCRIPT               339
#define IDB_BITMAP_SCRIPT_DISABLE       340
#define IDD_DIALOG_SCENE_PROPERTIES     341
#define IDC_RICHEDIT21                  1001
#define IDC_RICHEDIT22                  1002
#define IDC_RICHEDIT23                  1003
#define IDC_BTN_NORMALMAP               1006
#define IDC_BTN_GLOSSMAP                1007
#define IDC_BTN_ALPHAMAP                1008
#define IDC_EDIT_NORMALMAP              1009
#define IDC_EDIT_GLOSSMAP               1010
#define IDC_EDIT_ALPHAMAP               1011
#define IDC_BTN_HEIGHTMAP               1012
#define IDC_EDIT_HEIGHTMAP              1013
#define IDC_BTN_DUDVMAP                 1014
#define IDC_EDIT_DUDVMAP                1015
#define IDC_STATIC_MAPS                 1016
#define IDC_BTN_SHADOWMAP               1016
#define IDC_EDIT_SHADOWMAP              1017
#define IDC_BTN_DIRTMAP                 1018
#define IDC_EDIT1                       1019
#define IDC_EDIT_WATER_DUDV             1019
#define IDC_EDIT_DIRTMAP                1019
#define IDC_EDIT_AMBIENT_SOUND          1019
#define IDC_EDIT_AMBIENT_SOUND_BUFFER   1019
#define IDC_EDIT_SHADOW_SPLITWEIGHT     1019
#define IDC_EDIT_LIGHT_TOLERANCE        1019
#define IDC_EDIT19                      1020
#define IDC_EDIT_LIGHT_POS_X            1020
#define IDC_EDIT_WATER_NORMAL           1020
#define IDC_BTN_REMOVE_SCENE            1020
#define IDC_EDIT_SHADOW_NEARCLIPPLANE   1020
#define IDC_EDIT2                       1021
#define IDC_EDIT_LIGHT_AMBIENT_COLOR    1021
#define IDC_BTN_REMOVE_OBJECT           1021
#define IDC_EDIT_STATIC_SOUND_NAME      1021
#define IDC_EDIT_AMBIENT_SOUND_NAME     1021
#define IDC_EDIT_SHADOW_FARCLIPPLANE2   1021
#define IDC_EDIT_SHADOW_FARCLIPPLANE    1021
#define IDC_EDIT_NORMALMAP_BIAS         1021
#define IDC_EDIT3                       1022
#define IDC_EDIT_LIGHT_DIFFUSE_COLOR    1022
#define IDC_BTN_NORMALMAP2              1022
#define IDC_BTN_DELETE_NORMALMAP        1022
#define IDC_EDIT_STATIC_SOUND_X_POS     1022
#define IDC_EDIT_WATER_NAME             1022
#define IDC_EDIT_AMBIENT_SOUND_NAME2    1022
#define IDC_EDIT_AMBIENT_SOUND_VOLUME   1022
#define IDC_EDIT_SHADOW_INTENSITY       1022
#define IDC_EDIT4                       1023
#define IDC_EDIT_LIGHT_SPECULAR_COLOR   1023
#define IDC_BTN_DELETE_GLOSSMAP         1023
#define IDC_EDIT_STATIC_SOUND_PITCH     1023
#define IDC_EDIT_AMBIENT_SOUND_PITCH    1023
#define IDC_EDIT_WATER_UV               1023
#define IDC_EDIT5                       1024
#define IDC_BTN_DELETE_ALPHAMAP         1024
#define IDC_EDIT_STATIC_SOUND_DATA      1024
#define IDC_EDIT_WATER_SPEED            1024
#define IDC_EDIT_LIGHT_NAME             1024
#define IDC_EDIT6                       1025
#define IDC_BTN_DELETE_DUDVMAP          1025
#define IDC_EDIT_STATIC_SOUND_Y_POS     1025
#define IDC_EDIT_WATER_HEIGHT           1025
#define IDC_EDIT_NORMALMAP_SCALE        1025
#define IDC_EDIT7                       1026
#define IDC_BTN_DELETE_DIRTMAP          1026
#define IDC_EDIT_STATIC_SOUND_Z_POS     1026
#define IDC_EDIT_WATER_CENTER_X         1026
#define IDC_EDIT8                       1027
#define IDC_BTN_DELETE_SHADOWMAP        1027
#define IDC_EDIT_STATIC_SOUND_ROLLOFF   1027
#define IDC_EDIT_WATER_CENTER_Y         1027
#define IDC_EDIT9                       1028
#define IDC_BTN_DELETE_HEIGHTMAP        1028
#define IDC_EDIT_STATIC_SOUND_VOLUME    1028
#define IDC_EDIT_WATER_CENTER_Z         1028
#define IDC_EDIT10                      1029
#define IDC_EDIT_QUAD_ATTENUATION       1029
#define IDC_BTN_REMOVE_ENGINE_OBJECT    1029
#define IDC_EDIT_WATER_SCALE            1029
#define IDC_EDIT11                      1030
#define IDC_EDIT_CONSTANT_ATTENUATION   1030
#define IDC_EDIT_STATIC_SOUND_REFERENCE_DISTANCE 1030
#define IDC_BTN_ENGINE_OBJECT_PROPERTIES 1030
#define IDC_EDIT_WATER_LIGHT_X          1030
#define IDC_EDIT12                      1031
#define IDC_EDIT_LINEAR_ATTENUATION     1031
#define IDC_EDIT_STATIC_SOUND_MAX_DISTANCE 1031
#define IDC_EDIT_WATER_LIGHT_Y          1031
#define IDC_BTN_DIFFUSE                 1031
#define IDC_BTN_REMOVE_PHYSX            1031
#define IDC_EDIT13                      1032
#define IDC_EDIT_SPOT_CUTOFF            1032
#define IDC_EDIT_WATER_LIGHT_Z          1032
#define IDC_EDIT_DIFFUSE                1032
#define IDC_BTN_SCENE_PROPERTIES        1032
#define IDC_EDIT14                      1033
#define IDC_EDIT_SPOT_EXPONENT          1033
#define IDC_BTN_DELETE_DIFFUSE          1033
#define IDC_EDIT15                      1034
#define IDC_EDIT_SPOT_DIRECTION_X       1034
#define IDC_EDIT_PHYSX_PERCENTAGE       1034
#define IDC_EDIT16                      1035
#define IDC_EDIT_SHININESS              1035
#define IDC_BTN_DELETE_PHYSX            1035
#define IDC_EDIT17                      1036
#define IDC_EDIT_DIFFUSE2               1036
#define IDC_EDIT_PHYSX                  1036
#define IDC_EDIT18                      1037
#define IDC_EDIT_PHYSX_DENSITY          1037
#define IDC_EDIT20                      1038
#define IDC_EDIT_LIGHT_POS_Y            1038
#define IDC_EDIT21                      1039
#define IDC_EDIT_SPOT_DIRECTION_Y       1039
#define IDC_EDIT22                      1040
#define IDC_EDIT_LIGHT_POS_Z            1040
#define IDC_EDIT_NORMALMAP8             1040
#define IDC_BUTTON1                     1041
#define IDC_BUTTON_AMBIENT_LIGHT        1041
#define IDC_BUTTON_STATIC_SOUND_DATA    1041
#define IDC_BTN_NEW                     1041
#define IDC_WELCOME_BUTTON_CHECK        1041
#define IDC_BUTTON_DIFFUSE_LIGHT        1042
#define IDC_BTN_SAVE                    1042
#define IDC_WELCOME_BUTTON_HELP         1042
#define IDC_EDIT_SPOT_DIRECTION_Z       1043
#define IDC_BTN_COLLADA                 1043
#define IDC_WELCOME_BUTTON_UNCHECK      1043
#define IDC_BUTTON_SPECULAR_LIGHT       1044
#define IDC_BTN_PHYSX                   1044
#define IDC_COMB_LIGHT_TYPE             1045
#define IDC_BTN_ANIM_PREV               1045
#define IDC_WELCOME_BUTTON_VIDEO        1045
#define IDC_BTN_OPEN                    1046
#define IDC_WELCOME_BUTTON_TUTORIALS    1046
#define IDC_STATIC_MATERIAL             1047
#define IDC_BTN_SAVEAS                  1047
#define IDC_WELCOME_BUTTON_VANDA_OVERVIEW 1047
#define IDC_STATIC_SCENES               1048
#define IDC_LIST_SCENES                 1049
#define IDC_LIST_OBJECTS                1050
#define IDC_STATIC_OBJECTS              1051
#define IDC_STATIC_ENGINE_OBJECTS       1052
#define IDC_LIST_ENGINE_OBJECTS         1053
#define IDC_BTN_ANIM_PLAY               1054
#define IDC_BTN_ANIM_NEXT               1055
#define IDC_BTN_TIMER                   1056
#define IDC_BTN_ANIM_PAUSE              1057
#define IDC_BTN_WEB                     1058
#define IDC_BTN_WEB2                    1059
#define IDC_BTN_FACEBOOK                1059
#define IDC_STATIC_SELECTEDOBJECT       1060
#define IDC_BTN_WATER                   1061
#define IDC_CHECK_CULL_FACES            1062
#define IDC_BTN_MATERIAL                1062
#define IDC_BTN_SKY                     1063
#define IDC_BTN_AMBIENTSOUND            1064
#define IDC_BTN_STATICSOUND             1065
#define IDC_COMBO_STATIC_SOUND_LOOP     1066
#define IDC_BTN_PLAYER                  1066
#define IDC_COMBO_STATIC_SOUND_PLAY     1067
#define IDC_EDIT_SKYDOME_NAME           1067
#define IDC_BTN_LIGHT                   1067
#define IDC_EDIT_SKYDOME_X_POS          1068
#define IDC_BTN_CONSOLE                 1068
#define IDC_EDIT_SKYDOME_Y_POS          1069
#define IDC_BTN_SUMMARY                 1069
#define IDC_EDIT_SKYDOME_Z_POS          1070
#define IDC_STATIC_PHYSX_ELEMENTS       1070
#define IDC_EDIT_SKYDOME_RADIUS         1071
#define IDC_LIST_PHYSX_ELEMENTS         1071
#define ID_BUTTON_SKYDOM_PATH           1072
#define IDC_BTN_VANDA_TEXT              1072
#define IDC_EDIT_SKYDOM_PATH            1073
#define IDC_BTN_TWITTER                 1073
#define IDC_EDIT_SKYDOME_SLICES         1074
#define IDC_BTN_YOUTUBE                 1074
#define IDC_EDIT_SKYDOME_SIDES          1075
#define IDC_BTN_PUBLISH_SOLUTION        1075
#define IDC_EDIT_SKYDOME_DAMPENING      1076
#define IDC_LIST_WATER_ATTACHMENT       1076
#define IDC_BTN_SCRIPT_MANAGER          1076
#define IDC_COMBO_SKYDOM_EXPONENTIAL    1077
#define IDC_LIST_SELECT_CAMERA          1077
#define IDC_BTN_CAMERA_RENDERING_MANAGER 1077
#define IDC_LIST_AVAILABLE_SCENES       1077
#define IDC_CHECK1                      1078
#define IDC_SHADOW_ENABLECHECK          1078
#define IDC_CHECK_USE_AMBIENT           1078
#define IDC_BTN_VANDA_VERSION           1078
#define IDC_CHECK_TRIGGER               1078
#define IDC_CHECK_SAVE                  1078
#define IDC_COMBO2                      1081
#define IDC_COMBO_TRANSLATEPLANE        1081
#define IDC_RICHEDIT_CONSOLE            1082
#define IDC_COMBO_SHADOW_RENDERINGALGORITHM 1083
#define IDC_EDIT_FOCAL_DISTANCE         1084
#define IDC_COMBO_SHADOW_SPLITS         1085
#define IDC_EDIT_FOCAL_RANGE            1085
#define IDC_COMBO_SHADOW_RESOLUTION     1086
#define IDC_DOF_ENABLECHECK             1086
#define De                              1087
#define IDC_EDIT_FOG_COLOR              1087
#define IDC_COMBO_SHADOW_RESOLUTION2    1087
#define IDC_COMBO_SHADOW_DIRECTIONAL_LIGHT 1087
#define IDC_BUTTON_FOG_COLOR            1088
#define IDC_EDIT_FOG_DENSITY            1089
#define IDC_FOG_ENABLECHECK             1090
#define IDC_BLOOM_ENABLECHECK           1091
#define IDC_BUTTON2                     1092
#define IDC_BLOOM_COLOR                 1095
#define IDC_BLOOM_INTENSITY             1096
#define IDC_BUTTON_BLOOM_COLOR          1097
#define IDC_OPTIONS_SHADERCHECK         1098
#define IDC_COMBO_OPTIONS_NUMSAMPLES    1099
#define IDC_COMBO_OPTIONS_NUMANISOTROPY 1100
#define IDC_OPTIONS_MULTISAMPLECHECK    1101
#define IDC_OPTIONS_ANISOTROPYECHECK    1102
#define IDC_OPTIONS_FBOCHECK            1103
#define IDC_OPTIONS_VBOCHECK            1104
#define IDC_OPTIONS_VSYNCCHECK          1105
#define IDC_OPTIONS_WATERREFLECTIONCHECK 1106
#define IDC_OPTIONS_SHOWWELCOMEDIALOGCHECK 1107
#define IDC_LIST2                       1109
#define IDC_EDIT_MESH_PATH              1110
#define IDC_EDIT_DIFFUSE_TEXTURES       1111
#define IDC_EDIT_AMBIENT_COLOR          1111
#define IDC_EDIT_WATER_TEXTURES         1112
#define IDC_BUTTON_AMBIENT              1112
#define IDC_EDIT_SOUND_PATH             1113
#define IDC_COMBO_PHYSX                 1113
#define IDC_EDIT_EXTRA_TEXTURES         1114
#define IDC_EDIT_SKY_TEXTURE            1115
#define IDC_EDIT_PHYSX_PATH             1116
#define IDC_EDIT_NORMALMAP_NAME         1117
#define IDC_EDIT_ALPHAMAP_NAME          1118
#define IDC_EDIT_DIRTMAP_NAME           1119
#define IDC_BTN_LOADING_BANNER          1120
#define IDC_EDIT_GLOSSMAP_NAME          1121
#define IDC_EDIT_SCENEMANAGER_OBJECT_PER_SPLIT 1121
#define IDC_EDIT_SHADOWMAP_NAME         1122
#define IDC_EDIT_DESTINATION            1122
#define IDC_EDIT_MESH_PATH2             1123
#define IDC_EDIT_ICON                   1123
#define IDC_BTN_DESTINATION             1124
#define IDC_EDIT_DIFFUSE_EXCEPT         1124
#define IDC_EDIT_SETPASSWORD            1125
#define IDC_BTN_ICON                    1125
#define IDC_BTN_GENERATE_RANDOM_STRING  1126
#define IDC_EDIT_NAME                   1126
#define IDC_LIST_SCENES_TO_PUBLISH      1127
#define IDADD                           1128
#define IDREMOVE                        1129
#define IDC_BTN_SPLASH_IMAGE            1130
#define IDC_EDIT_SPLASH_LOGO            1131
#define IDC_BTN_TRIGGER_ENTER           1131
#define IDADD2                          1132
#define ID_MARK_AS_FIRST_SCENE          1132
#define IDC_BTN_TRIGGER_EXIT            1133
#define IDC_EDIT_TRIGGER_ENTER          1134
#define IDC_EDIT_TRIGGER_EXIT           1135
#define IDC_BTN_DELETE_TRIGGER_ENTER    1137
#define IDC_BTN_DELETE_TRIGGER_REMOVE   1139
#define IDC_RICHEDIT_REPORT_SCRIPT_INFO 1140
#define IDC_PLAY_ANIMATION_ENABLECHECK  1141
#define IDC_PLAY_ANIMATION_ENABLECHECK2 1142
#define IDC_LOOP_ANIMATION_ENABLECHECK2 1142
#define IDC_COMBO_ANIMATION_CLIP        1143
#define Can                             1144
#define ID_FILE_SAVE32771               32771
#define ID_HELP_ABOUTHARMONICENGIINE    32772
#define ID_FILE_SAVEAS                  32773
#define ID_FILE_SAVE32774               32774
#define ID_FILE_SAVEAS32775             32775
#define ID_FILE_IMPORT                  32776
#define ID_FILE_EXIT                    32777
#define ID_EDIT_TRANSLATE               32778
#define ID_EDIT_ROTATE                  32779
#define ID_EDIT_SCALE                   32780
#define ID_INSTERT_LIGHT                32781
#define ID_LIGHT_POINTLIGHT             32782
#define ID_LIGHT_DIRECTIONAL            32783
#define ID_LIGHT_SPOT                   32784
#define ID_INSERT_CAMERA                32785
#define ID_LIGHT_AMBIENT                32786
#define ID_IMPORT_COLLADA               32787
#define ID_INSERT_SOUND                 32788
#define ID_WINDOW_JUSTPERSPECTIVE       32789
#define ID_WINDOW_ALL                   32790
#define ID_TOOLS_SHADER                 32791
#define ID_WINDOW_SWITCH                32792
#define ID_TOOLS_MULTISAMPLING          32793
#define ID_VIEW_LIGHTSOURCES            32794
#define ID_VIEW_SOUNDSOURCES            32795
#define ID_VIEW_PERSPECTIVEGRIDS        32796
#define ID_VIEW_LIGHT_POSITIONS         32797
#define ID_VIEW_SOUND_POSITIONS         32798
#define ID_VIEW_PERSPECTIVE_GRIDS       32799
#define ID_TOOLS_VBO                    32800
#define ID_TOOLS_FOG                    32801
#define ID_INSERT_LIGHT                 32802
#define ID_VIEW_BOUNDINGBOX             32803
#define ID_INSERT_                      32804
#define ID_SKY_SKYDOME                  32805
#define ID_SKY_SKYBOX                   32806
#define ID_SKY_SKYPLANE                 32807
#define ID_INSERT_SKYDOME               32808
#define ID_INSERT_WATER                 32809
#define ID_SOUND_AMBIENTSOUND           32810
#define ID_PHYSICS_DEBUGMODE            32811
#define ID_TOOLS_SOUND                  32812
#define ID_SOUND_AMBIENT                32813
#define ID_ONSERT_SOUND_AMBIENTSOUND    32814
#define ID_INSERT_SOUND_AMBIENTSOUND    32815
#define ID_INSERT_SOUND_AMBIENT         32816
#define ID_TOOLS_SOUND_AMBIENT          32817
#define ID_HELP_ABOUT                   32818
#define ID_HELP_HOMEPAGE                32819
#define ID_TOOLS_CULLFACE               32820
#define ID_TOOLS_CULLFACES              32821
#define ID_TOOLS_FBO                    32822
#define ID_EFFECTS_WATERREFLECTION      32823
#define ID_EFFECTS_GLOW                 32824
#define ID_EFFECTS_BLOOM                32825
#define ID_IMPORT_PHYSX                 32826
#define ID_TOOLS_CAMERASPEED            32827
#define ID_CAMERASPEED_INCREASE         32828
#define ID_CAMERASPEED_DECREASE         32829
#define ID_CAMERASPEED_DEFAULT          32830
#define ID_TOOLS_CAMERASPEED_INCREASE   32831
#define ID_TOOLS_CAMERASPEED_DECREASE   32832
#define ID_TOOLS_CAMERASPEED_DEFAULT    32833
#define ID_TOOLS_CAMERAZOOM             32834
#define ID_CAMERAZOOM_DEFAULT           32835
#define ID_TOOLS_CAMERAZOOM_DEFAULT     32836
#define ID_SOUND_STATICSOUND            32837
#define ID_INSERT_SOUND_STATICSOUND     32838
#define ID_INSERT_SOUND_STATIC          32839
#define ID_TOOLS_ATTACHTO               32840
#define ID_ATTACHTO_WATER               32841
#define ID_TOOLS_DETACHFROM             32842
#define ID_DETACHFROM_WATER             32843
#define ID_TOOLS_WATER_ATTA             32844
#define ID_TOOLS_WATERATTACHMENT        32845
#define ID_TOOLS_SELECTCAMERA           32846
#define ID_EFFECTS_DEPTHOFFIELD         32847
#define ID_EFFECTS_DOF                  32848
#define ID_TOOLS_SHADOW                 32849
#define ID_SHADOW_RESOLUTION            32850
#define ID_RESOLUTION_1024              32851
#define ID_RESOLUTION_2048              32852
#define ID_RESOLUTION_4096              32853
#define ID_SHADOW_ENABLE                32854
#define ID_SHADOW_TYPE                  32855
#define ID_TYPE_PCFGAUSSIAN             32856
#define ID_SHADOW_VIEWDEPTHMAP          32857
#define ID_TYPE_DEBUG                   32858
#define ID_SHADOW_TYPE_DEBUG            32859
#define ID_SHADOW_TYPE_PCFGAUSSIAN      32860
#define ID_SHADOW_RESOLUTION_1024       32861
#define ID_SHADOW_RESOLUTION_2048       32862
#define ID_SHADOW_RESOLUTION_4096       32863
#define ID_VIEW_SHADOWDEPTHMAP          32864
#define ID_VIEW_BLURDEPTHMAP            32865
#define ID_TOOLS_DEPTHOFFIELD           32866
#define ID_SHADOW_SPLITS                32867
#define ID_SPLITS_1                     32868
#define ID_SPLITS_2                     32869
#define ID_SPLITS_3                     32870
#define ID_SPLITS_4                     32871
#define ID_SHADOW_SPLITWEIGHT           32872
#define ID_SHADOW_SPLITS_1              32873
#define ID_SHADOW_SPLITS_2              32874
#define ID_SHADOW_SPLITS_3              32875
#define ID_SHADOW_SPLITS_4              32876
#define ID_TYPE_PCF                     32877
#define ID_SHADOW_TYPE_PCF              32878
#define ID_TYPE_SIMPLE                  32879
#define ID_SHADOW_TYPE_SIMPLE           32880
#define ID_Menu                         32881
#define ID_SHADOW_PCF_TRILIN            32882
#define ID_SHADOW_TYPE_PCF_TRILIN       32883
#define ID_SHADOW_TYPE_PCF_GAUSSIAN     32884
#define ID_TYPE_PCF4TAP                 32885
#define ID_TYPE_PCF8TAP                 32886
#define ID_TYPE_LEAK                    32887
#define ID_TYPE_NOLEAK                  32888
#define ID_SHADOW_TYPE_LEAK             32889
#define ID_SHADOW_TYPE_NOLEAK           32890
#define ID_SHADOW_TYPE_PCF4TAP          32891
#define ID_SHADOW_TYPE_PCF8TAP          32892
#define ID_SHADOW_TYPE_PCF_4TAP         32893
#define ID_SHADOW_TYPE_PCF_8TAP         32894
#define ID_INSERT_PLAYER                32895
#define ID_PHYSICS_APPLYGRAVITY         32896
#define ID_TOOLS_GEOMETRYBASEDSELECTION 32897
#define ID_FOG_ENABLE                   32898
#define ID_TOOLS_FOG_ENABLE             32899
#define ID_FOG_PROPERTIES               32900
#define ID_TOOLS_FOG_PROPERTIES         32901
#define ID_VIEW_STATISTICS              32902
#define ID_CAMERA_DEFAULTZOOM           32903
#define ID_HELP_ONLINEHELP              32904
#define ID_TOOLS_MATERIALEDITOR         32905
#define ID_VIEW_ICONS                   32906
#define ID_VIEW_REPORTDETAILS           32907
#define ID_VIEW_WARNINGSANDERRORS       32908
#define ID_VIEW_REPORT                  32909
#define ID_ICONS_SKYICON                32910
#define ID_ICONS_WATERICONS             32911
#define ID_WINDOW_LAYOUTS               32912
#define ID_LAYOUTS_4SPLIT               32913
#define ID_LAYOUTS_PERSPECTIVE          32914
#define ID_EDIT_BLOOM                   32915
#define ID_EDIT_WATER                   32916
#define ID_WATER_WATERREFLECTION        32917
#define ID_EDIT_AMBIENTSOUND            32918
#define ID_AMBIENTSOUND_PROPERTIES      32919
#define ID_BLOOM_PROPERTIES             32920
#define ID_DEPTHOFFIELD_PROPERTIES      32921
#define ID_CAMERA_PROPERTIES            32922
#define ID_MODIFY_ENGINEOPTIONS         32923
#define ID_MODIFY_GEOMETRY              32924
#define ID_MODIFY_SHADOW                32925
#define ID_MODIFY_DOF                   32926
#define ID_MODIFY_FOG                   32927
#define ID_MODIFY_BLOOM                 32928
#define ID_TOOLS_OPTIONS                32929
#define ID_VIEW_ALLCHANNELS             32930
#define ID_VIEW_DIFFUSECHANNEL          32931
#define ID_VIEW_NORMALMAPCHANNEL        32932
#define ID_VIEW_GLOSSMAPCHANNEL         32933
#define ID_VIEW_SHADOWMAPCHANNEL        32934
#define ID_VIEW_DIRTMAPCHANNEL          32935
#define ID_VIEW_CHANNELS                32936
#define ID_CHANNELS_ALPHAMAPCHANNEL     32937
#define ID_VIEW_NORMALVECTORS           32938
#define ID_VIEW_VERTEXPOSITIONS         32939
#define ID_VIEW_ALPHAMAPCHANNEL         32940
#define ID_VIEW_OCTREE                  32941
#define ID_VIEW_POLGYGONMODE            32942
#define ID_POLGYGONMODE_FILL            32943
#define ID_POLGYGONMODE_LINE            32944
#define ID_POLGYGONMODE_POINT           32945
#define ID_MODIFY_LIGHT                 32946
#define ID_ICONS_CAMERAICONS            32947
#define ID_TOOLS_SCENEOPTIONS           32948
#define ID_GEOMETRY_AMBIENTCOLOR        32949
#define ID_FILE_PUBLISHSOLUTION         32950
#define ID_TOOLS_SCRIPTMANAGER          32951
#define ID_MODIFY_SCENEMANAGER          32952

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        342
#define _APS_NEXT_COMMAND_VALUE         32953
#define _APS_NEXT_CONTROL_VALUE         1145
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
